import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/layout/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import "./globals.css"
import Footer from "@/components/layout/Footer"
import MiguruFAB from "@/components/miguruai/MiguruFAB"

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <MiguruFAB />
      </body>
    </html>
  )
}
